name: My Github Actions Workflow
on: 
  push:
    branches:
      - main

env: 
  GREETING: "Hello, World! naveen rahil"
  course: "GitHub Actions"


jobs:
  my_first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Greet the world
        run: echo "Hello, World!"
      
      - run: echo "Print environment variables"
      - name: Print environment variables
        run: |
          echo "GREETING: $GREETING"
          echo "Course: $course"


      - run: echo "Job status"
      - run: echo "This job's status is ${{ job.status }}."

      - name: Display GitHub Context
        run: |
          echo "Event Name: ${{ github.event_name }}"
          echo "Runner OS: ${{ runner.os }}"
          echo "Branch Name: ${{ github.ref }}"
          echo "Repository: ${{ github.repository }}"

      - run: echo "ðŸŽ‰ The job was automatically triggered by a ${{ github.event_name }}"


